import colors from 'app/colors'

export default {
  wrap: {
    flex: 0,
    position: "relative",
    zIndex: 2,
    transition: "max-height 1600ms ease, flex 1600ms ease",
    borderTop: `1px solid ${colors.secondaryBorder}`,
    backgroundColor: colors.secondaryBackground,
    maxHeight: 0,
  },
  isActive: {
    transition: "maxHeight 1600ms ease, flex 1600ms ease",
    flex: 3,
    maxHeight: 1000,
  },
  input: {
    width: "100%",
    backgroundColor: "#FFF",
    borderStyle: "none",
    borderColor: "Transparent",
    borderRadius: 10,
    fontSize: 16,
    fontFamily: "inherit",
    padding: "10px",
    boxSizing: "border-box",
    margin: 0,
    resize: "none",
    outline: "none",
  },
  buttonsWrap: {
    display: "flex",
    flexDirection: "row",
    padding: "0 10px",
    marginBottom: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonInner: {
    flex: 1,
    textAlign: "right",
  },
  button: {
    padding: "7px 21px",
    display: "inline-block",
    fontSize: 14,
    textAlign: "center",
    border: 0,
    borderRadius: 10,
    backgroundColor: "#E0E0E0",
    color: "#9E9E9E",
    outline: "none",
  },
  buttonActive: {
    backgroundColor: "#8BC34A",
    color: "#FFF",
  },
  level1: {
    position: "relative",
    margin: "0 10px",
  },
  day: {
    display: "inline-block",
    padding: "0 15px",
    backgroundColor: "#EEEEEE",
    textAlign: "center",
    border: 0,
    fontSize: 14,
    lineHeight: "34px",
    borderRadius: 10,
    outline: "none",
    color: "inherit",
  },
  yesterday: {
    // borderRadius: "10px 0 0 10px",
  },
  today: {
    // borderRadius: "0 10px 10px 0",
  },
  dayIsActive: {
    backgroundColor: "#8BC34A",
    color: "#FFF",
  },
}
