export default {
  layer: {
    backgroundColor: "#121212",
    zIndex: 1,
    position: "fixed",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  categoryButton: {
    display: "inline-block",
    width: 100,
    height: 100,
    borderRadius: 100,
    lineHeight: "100px",
    textAlign: "center",
    border: 0,
    backgroundColor: "#FFF",
    margin: 5,
  },
  button: {
    padding: "10px 20px",
    borderRadius: 8,
    fontSize: 20,
    backgroundColor: "#FFF",
    border: "1px solid #333",
    display: "block",
    width: "100%",
    boxSizing: "border-box",
    margin: "5px 0",
  },
  select: {
    fontSize: 20,
    border: "1px solid #333",
  },
  textarea: {
    padding: "10px 20px",
    borderRadius: 8,
    fontSize: 20,
    backgroundColor: "#FFF",
    border: "1px solid #333",
    display: "block",
    width: "100%",
    boxSizing: "border-box",
    margin: "5px 0",
    minHeight: 100,
  },
}
