export default {
  chartToggle: {
    position: "fixed",
    lineHeight: "40px",
    height: 40,
    width: 60,
    bottom: 10,
    left: 0,
    fontSize: 20,
    display: "block",
    textAlign: "center",
    zIndex: 12,
    backgroundColor: "#212121",
    borderRadius: "0 20px 20px 0",
  },
  addIcon: {
    position: "fixed",
    bottom: 10,
    right: 10,
    margin: "auto",
    width: 50,
    height: 50,
    borderRadius: 50,
    lineHeight: "55px",
    fontSize: 30,
    display: "block",
    textAlign: "center",
    zIndex: 5,
  },
  closeIcon: {
    position: "fixed",
    bottom: 10,
    right: 10,
    fontSize: 30,
    display: "block",
    textAlign: "center",
    zIndex: 3,
  },
  container: {

  },
  days: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  trends: {
    position: "fixed",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    transition: "all 200ms ease",
    transform: "translateX(350px)",
    boxShadow: "1px 1px 30px #424242",
  },
  shouldShowTrends: {
    position: "absolute",
    transform: "translateX(0)",
  },
}
